### ISSUE TITLE
[edit] AttributeError: 'Stream' object has no attribute 'read_uart'

### ISSUE THREAD

**Issue by lucize** [straga/Smart-Meter-Gateway#3]
Hi @straga 

I'm having some issues with DEYE and reading correct CT values (3P, maybe the cable length is the issue here), it always uses some grid power, but if I setul with zero export to load and internal CT is used then no grid power is used, I would also like to use non protected load with correct CT information.

I know most of the addresses of the smart meter, where do I need to add the Modbus addresses  for this to work with the 3P Deye hybrid

Examples:

Deye external CT

![image](https://github.com/straga/Smart-Meter-Gateway/assets/6313831/f0ab221e-e1bf-40fd-b337-5375b3a7a321)

vs

![image](https://github.com/straga/Smart-Meter-Gateway/assets/6313831/61fcacc0-ef67-4a11-ae53-25941351f5f3)

also I'm not very documented on how to use this on an esp32, used until now only esphome and tasmota

**Comment by lucize** [comment]
ok, managed to understand what is this about but I'm stuck at

```
Traceback (most recent call last):
  File "uasyncio/core.py", line 1, in run_until_complete
  File "scrivo_meter/_runner.py", line 114, in meter_process
AttributeError: 'Stream' object has no attribute 'read_uart'
```
is related to some updates in micropython ?

**Comment by straga** [comment]
Hello.
use:
.read(1024)

чт, 30 нояб. 2023 г. в 05:14, Lucian CRISTIAN ***@***.***>:

**Comment by lucize** [comment]
yes! exactly 10 minutes ago I used read and seems that I got valid data
wasted hours to use readline(), thanks for the response 

tested on a CHINT, now I'll switch to WDYK smart circuit breaker and see how it will be

**Comment by lucize** [comment]
@straga what should be the proper way to find needed information ?
my deye asks this:
CHINT:

```
DEBUG:MODBUS: << pannel uart request: 01 03 20 14 00 06 8e 0c - 8
DEBUG:MODBUS:       crc check: 8e 0c
DEBUG:MODBUS:   addr: 1, func: 3, reg_addr: 8212, qty: 6 
DEBUG:MODBUS:   offset: 48213
```
```
DEBUG:MODBUS: << pannel uart request: 01 03 10 1e 00 0c 21 09 - 8
DEBUG:MODBUS:       crc check: 21 09
DEBUG:MODBUS:   addr: 1, func: 3, reg_addr: 4126, qty: 12 
DEBUG:MODBUS:   offset: 44127
```
and from time to time

```
DEBUG:MODBUS: << pannel uart request: 01 03 10 1e 00 0c 21 09 01 03 20 14 00 06 8e 0c 01 03 10 1e 00 0c 21 09 01 03 20 14 00 06 8e 0c 01 03 10 1e 00 0c 21 09 - 40
DEBUG:MODBUS:error: HEX: 'NoneType' object isn't iterable
DEBUG:MODBUS:       crc check: None
```

for eastron

```
DEBUG:MODBUS: << pannel uart request: 01 04 00 0c 00 06 b0 0b - 8
DEBUG:MODBUS:       crc check: b0 0b
DEBUG:MODBUS:   addr: 1, func: 4, reg_addr: 12, qty: 6 
DEBUG:MODBUS:   offset: 30013
```
```
DEBUG:MODBUS: << pannel uart request: 01 04 00 48 00 04 71 df - 8
DEBUG:MODBUS:       crc check: 71 df
DEBUG:MODBUS:   addr: 1, func: 4, reg_addr: 72, qty: 4 
DEBUG:MODBUS:   offset: 30073
```
and from time to time

```
DEBUG:MODBUS: << pannel uart request: 01 04 00 0c 00 06 b0 0b 01 04 00 48 00 04 71 df 01 04 00 0c 00 06 b0 0b 01 04 00 48 00 04 71 df 01 04 00 0c 00 06 b0 0b - 40
DEBUG:MODBUS:error: HEX: 'NoneType' object isn't iterable
DEBUG:MODBUS:       crc check: None

```

my smart meter has this registers

Read Holding-Register(modbus function code=03)

0011	Total-Active-Power	HEX,unit0.01KW
0012	Active-Power(A-Phase)	HEX,unit0.01KW
0013	Active-Power(B-Phase)	HEX,unit0.01KW
0014	Active-Power(C-Phase)	HEX,unit0.01KW
0015	Total-Reactive-Power	HEX,unit0.01Kvar
0016	Reactive-Power(A-Phase)	HEX,unit0.01Kvar
0017	Reactive-Power(B-Phase)	HEX,unit0.01Kvar
0018	Reactive-Power(C-Phase)	HEX,unit0.01Kvar
0021	Positive-Active-PowerConsumption1/2	2Register，4Byte，HEX,unit0.01KWh
0022	Positive-Active-PowerConsumption2/2	
0023	Negative-Active-PowerConsumption 1/2	2Register，4Byte，HEX,unit0.01KWh
0024	Negative-Active-PowerConsumption 2/2	

the only way to find out the needed format of the values is to sniff the chint meter?
can I do this if I only have 2 wires without ground ?
in fact, I could just ask the meter via the uart in `async def meter_process(self):` and see what type of response I get from the chint

**Comment by kommando828** [comment]
RS485 will work with 2 wires for short distances, the ground just gives a central datum for the voltage signals as they vary + to- . Adding a 120ohm resistor between the 2 at the meter RS485 wires can help too as well as using shielded cable but I have successfully used 2 unshielded untwisted wires with no ground and no resistor up to 1M. If you are using a PC to sniff then the best program is this

https://github.com/SciFiDryer/ModbusMechanic

Note the Java install requirement

**Comment by lucize** [comment]
So i have these values

```
INFO:MODBUS: << uart Meter: 01 03 0c 42 94 00 00 00 00 00 00 00 00 00 00 83 ba
DEBUG:MODBUS:unit_addr: 1, reg_offset: 48213, byte_qty: 12, data: 01 03 0c 42 94 00 00 00 00 00 00 00 00 00 00
DEBUG:MODBUS:<<meter recv value data: 42 94 00 00 00 00 00 00 00 00 00 00

01	                                Slave address	0x01 (1)
03	                                Function code	0x03 (3) - Read Holding Registers
0C	                                Byte count	0x0C (12)
42 94 00 00 00 00 00 00 00 00 00 00	Register value	0x4294 (17044), 0x0000 (0), 0x0000 (0), 0x0000 (0), 0x0000 (0), 0x0000 (0)
83 BA	                                CRC	0x83BA (33722)
```

```
INFO:MODBUS: << uart Meter: 01 03 18 43 b3 16 b8 43 1b 16 66 42 cb 48 f6 42 ca e5 1f 43 a9 f6 b8 41 cb 4c cd dc 2e
DEBUG:MODBUS:unit_addr: 1, reg_offset: 44127, byte_qty: 24, data: 01 03 18 43 b3 16 b8 43 1b 16 66 42 cb 48 f6 42 ca e5 1f 43 a9 f6 b8 41 cb 4c cd
DEBUG:MODBUS:<<meter recv value data: 43 b3 16 b8 43 1b 16 66 42 cb 48 f6 42 ca e5 1f 43 a9 f6 b8 41 cb 4c cd

01	                                                                Slave address	0x01 (1)
03	                                                                Function code	0x03 (3) - Read Holding Registers
18	                                                                Byte count	0x18 (24)
43 B3 16 B8 43 1B 16 66 42 CB 48 F6 42 CA E5 1F 43 A9 F6 B8 41 CB 4C CD	Register value	0x43B3 (17331), 0x16B8 (5816), 0x431B (17179), 0x1666 (5734), 0x42CB (17099), 0x48F6 (18678), 0x42CA (17098), 0xE51F (58655), 0x43A9 (17321), 0xF6B8 (63160), 0x41CB (16843), 0x4CCD (19661)
DC 2E	                                                                CRC	0xDC2E (56366)
```

my issue is how should I combine multiple read registers and come with this format and also I need to use CRC on the data ?

**Comment by lucize** [comment]
tried to put this interface between chint and deye and it seems that deye doesn't like the response from esp32, I guess I have to sniff packets when chint is directly connected

chint is a borrowed meter and I would like not to add one to my existing instalation

```
data_request = {
    "deye_chint_3p": {
        "addr": 1,
        "func": 3,
        "start_reg": 8212,
        "qty_reg": 6,
        "alive": 0,
        "raw": 0x00,
    },

    "deye_chint_3p_r": {
        "addr": 1,
        "func": 3,
        "start_reg": 4126,
        "qty_reg": 12,
        "alive": 0,
        "raw": 0x00,
    }
}

data_register_master = {

    44127: {
        "alive": 0,
        "raw": b'\x00',
        "value": 0,
        "act": None,
    },
    48213: {
        "alive": 0,
        "raw": b'\x00',
        "value": 0,
        "act": None,
    },
}


data_register_slave = {
    48213: {
        "master": 48213,
        "func": 0x03,
        "act": None
    },
    44127: {
        "master": 44127,
        "func": 0x03,
        "act": None
    },
}

```

```
INFO:MODBUS: << uart Meter: 01 03 0c 42 9e 00 00 00 00 00 00 00 00 00 00 a2 62
DEBUG:MODBUS:unit_addr: 1, reg_offset: 48213, byte_qty: 12, data: 01 03 0c 42 9e 00 00 00 00 00 00 00 00 00 00
DEBUG:MODBUS:<<meter recv value data: 42 9e 00 00 00 00 00 00 00 00 00 00
DEBUG:MODBUS: 
DEBUG:MODBUS: << pannel uart request: 01 03 10 1e 00 0c 21 09 - 8
DEBUG:MODBUS:       crc check: 21 09
DEBUG:MODBUS:   addr: 1, func: 3, reg_addr: 4126, qty: 12 
DEBUG:MODBUS:   offset: 44127
DEBUG:MODBUS:   - alive: 10
DEBUG:MODBUS:  panel Modbus raw: 43 b3 17 0a 43 1b 17 0a 42 cb 48 f6 42 ca e5 1f 43 a9 f7 0a 41 cb 4c cd


DEBUG:MODBUS: Meter Pdu UART : 01 03 20 14 00 06 8e 0c
DEBUG:MODBUS: 
DEBUG:MODBUS:unit_addr: 1, reg_offset: 48213, byte_qty: 12, data: 01 03 0c 42 9e 00 00 00 00 00 00 00 00 00 00
DEBUG:MODBUS:<<meter recv value data: 42 9e 00 00 00 00 00 00 00 00 00 00
DEBUG:MODBUS: << pannel uart request: 01 03 20 14 00 06 8e 0c - 8
DEBUG:MODBUS:       crc check: 8e 0c
DEBUG:MODBUS:   addr: 1, func: 3, reg_addr: 8212, qty: 6 
DEBUG:MODBUS:   offset: 48213
DEBUG:MODBUS:   - alive: 10
DEBUG:MODBUS:  panel Modbus raw: 42 9e 00 00 00 00 00 00 00 00 00 00

```

**Comment by lucize** [comment]
so I did a sniffing and this seems to repeat

I don't know how to interpret what are the other two responses, but also using ModbusMechanic I can see only two register reads and one write (8213,4126 and 286)


```
[04/12/2023 20:58:56] 
Modbus Response (COM4) 
Address: 1 
Function: 3 (0x03) - Read Holding Registers 
    Byte Count: 12 
    Values: 42 9c 00 00 00 00 00 00 00 00 00 00  
        Register0: 17052 
        Register1: 0 
        Register2: 0 
        Register3: 0 
        Register4: 0 
        Register5: 0 
Checksum: 43482(OK) 
---------------------------------------------------------------------------------- 
[04/12/2023 20:58:57] 
Modbus Response (COM4) 
Address: 171 
Function: 16 (0x10) - Write Multiple Registers 
    Starting Address: 286 
    Quantity: 2 
Checksum: 56475(OK) 
---------------------------------------------------------------------------------- 
[04/12/2023 20:58:57] 
Modbus Response (COM4) 
Address: 1 
Function: 3 (0x03) - Read Holding Registers 
    Byte Count: 16 
    Values: 1e 00 0c  
        Register0: 7680 
Checksum: 8457(OK) 
---------------------------------------------------------------------------------- 
[04/12/2023 20:58:57] 
Modbus Response (COM4) 
Address: 1 
Function: 3 (0x03) - Read Holding Registers 
    Byte Count: 24 
    Values: 43 b3 17 0a 43 1b 17 0a 42 cb 48 f6 42 ca e5 1f 43 a9 f7 0a 41 cb 4c cd  
        Register0: 17331 
        Register1: 5898 
        Register2: 17179 
        Register3: 5898 
        Register4: 17099 
        Register5: 18678 
        Register6: 17098 
        Register7: 58655 
        Register8: 17321 
        Register9: 63242 
        Register10: 16843 
        Register11: 19661 
Checksum: 17(OK) 
---------------------------------------------------------------------------------- 
[04/12/2023 20:58:57] 
Modbus Response (COM4) 
Address: 1 
Function: 3 (0x03) - Read Holding Registers 
    Byte Count: 32 
    Values: 14 00 06  
        Register0: 5120 
Checksum: 36364(OK) 
---------------------------------------------------------------------------------- 
```
```
AB                Slave address	        0xAB (171)
10                Function code	        0x10 (16) - Write Multiple Registers
01 1E             Starting address	Physical: 0x011E (286)
                                        Logical: 0x011F (287)
00 02             Quantity	        0x0002 (2)
04                Byte count	        0x04 (4)
00 C8 00 00       Registers value	0x00C8 (200), 0x0000 (0)
DC 9B             CRC	                0xDC9B (56475)
```

**Comment by lucize** [comment]
so tried to debug with sniffer activated
seems that there is no response back to inverter, the `make_pdu_response(unit_addr, reg_func, value_byte)` seems to never get called and the `await self.panel_swriter.awrite(pdu_response)` sends data without crc ? is this expected ?
adding the `hexh(pdu_response)` to a modbus decoder complains about missing bytes

if I force something like

```
DEBUG:MODBUS: Panel Modbus data:      00 00 00 00 00 01 00 0a 00 06 00 00
DEBUG:MODBUS: Panel Modbus Pdu: 01 03 00 00 00 00 00 01 00 0a 00 06 00 00 c6 c3
```
I get : `Expected data package size is 5 bytes.`

**Comment by straga** [comment]
Chint Meter no so good.
Now I am use only Eastron much better.
My Deye RS485 port meter dosn't work. Why I don't know. May after firmware inverter update or some wrong with port.

Hello.
May be you know.
I have connected to Meter Eastron3p. por RS485, pin 4 and 5. That works before, but now after communication wire or some other. I have error W04 meter comm fault. I am connect MODBUS alylizer and shows
![image](https://github.com/straga/Smart-Meter-Gateway/assets/34532/3046a361-1998-4d94-856f-386395b23e74)

First message when Inverter turn ON.
Second when turn On - use meter.


Any way, Deye not use special protocol for meter. Just use official modbus protocol from Meter. Need check documentation for each meter.

Also we can use to UART-RS485. And one connect to Inverter, second to Meter, And resend, log message between.

What main trouble now?

**Comment by kommando828** [comment]
Is you Deye RS485 port a RJ45 socket and you are using network cable for the connection.

I had the same issue with a Solax X1 Boost with RJ45 socket, the network cable was of solid copper wire not stranded wire and gave the same error plus the solid copper wire fatigued and broke several times. I established a connection by using Network Cat5e cable with 24awg stranded copper wire.

**Comment by straga** [comment]
Solax use own protocol. 
I change cable. Deye won't anymore connect with meter directly. Now I am connect CT on wire, that fork for Deye. From meter read data direct  to HomeAssistant over micropython board. 

I have new version with MQTT auto discovery for meter. Couple days I wll push to github.

**Comment by lucize** [comment]
Hi @straga my problem now is that the UART2 is not sending back packets, or the packets are not correctly formatted.
It receives the deye querry, but on the sniffer I don't see any reply from the micropython like I see if I connect directly the meter.
I see micropython sending reply on the UART2, I also see led blinking on the modbus to serial adapter, but the sniffer doesn't show any reply, so I think there is an issue whit the data sent back

**Comment by lucize** [comment]
I think this PR will better solve my issue and will be easier to setup https://github.com/esphome/esphome/pull/4874

**Comment by lucize** [comment]
using esphome modbus server PR and eastron mode seems to work as it should
